services:
  - type: web
    name: q-backend
    runtime: node
    repo: https://github.com/SineMag/Q # Replace with your repository URL
    region: oregon # optional, region closest to you
    plan: free # optional, see https://render.com/pricing
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 3001
      - key: DATABASE_URL
        fromDatabase:
          name: q-db
          property: connectionString
      - key: NODE_ENV
        value: production

databases:
  - name: q-db
    databaseName: q_healthcare
    plan: free # optional, see https://render.com/pricing
